name: stream-crm

services:
  postgres-projects:
    image: postgres:18
    container_name: postgres-projects
    restart: unless-stopped
    environment:
      POSTGRES_USER: streamCRMServerAdmin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_projects_data:/var/lib/postgresql
    networks:
      - stream-crm-network

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-stream-crm
    restart: unless-stopped
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_streamcrm_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 20s
    networks:
      - stream-crm-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.5.0
    container_name: es-local
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - stream-crm-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
  kibana:
    image: docker.elastic.co/kibana/kibana:9.5.0
    container_name: kibana-local
    restart: unless-stopped
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - stream-crm-network
  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: prometheus-local
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - promdata:/prometheus
  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana-local
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafanadata:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  postgres_projects_data:
    external: true
    name: stream-crm_postgres_projects_data

  rabbitmq_streamcrm_data:
  esdata:
  promdata:
  grafanadata:
networks:
  stream-crm-network:
    driver: bridge
