global:
  scrape_interval: 5s     # Cada cuánto tiempo Prometheus le pide datos a tus APIs
  evaluation_interval: 5s # Cada cuánto tiempo evalúa las reglas de alertas

scrape_configs:
  # 1. Métrica propia de Prometheus (Monitoreo interno)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Microservicio 1: Customer API (Corriendo en tu máquina física puerto 3000)
  - job_name: 'customers-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']

  # 3. Microservicio 2: Notification API (Por si tenés otra API en el puerto 3001)
  - job_name: 'notification-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3001']