export enum ApiErrorCode {
    NOT_FOUND = 'NOT_FOUND',
    CONFLICT_ERROR = 'CONFLICT_ERROR',
    BAD_REQUEST = 'BAD_REQUEST',
    CUSTOMER_EMAIL_DUPLICATED = 'CUSTOMER_EMAIL_DUPLICATED',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    CUSTOME_ERROR = 'CUSTOME_ERROR'
}